version: '2'
services:

  api:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
    - ./api:/var/www/api
    env_file:
    - .env
    ports:
    - 8083:8083
    depends_on:
      - redis
    #command: node -e "require('http').createServer().listen(1993,()=>{});"
    command: bash -c "cd api && npm start"

  # The Database
  database:
    image: mysql:latest
    volumes:
    - ./api/migrations:/migrations
    env_file:
    - .env
    ports:
        - "33062:3306"

  redis:
    image: redis:4.0.8
    ports:
        - "63791:6379"
  
# volumes:
#   dbdata: